### ISSUE TITLE
Problems in installing ydk-py in MacOS

### ISSUE THREAD

**Issue by khalilmebarkia** [CiscoDevNet/ydk-py#39]
I'm trying to install `ydk-py` in my machine, but unfortunately, It did not work. I followed every single instruction in here [ydk-py installation guide][1] and I have got the same error which is the following:

 

    -- Build files have been written to: /tmp/pip-req-build-iLuIe4/build/temp.macosx-10.6-x86_64-2.7
        Scanning dependencies of target ydk_
        [ 50%] Building CXX object CMakeFiles/ydk_.dir/python.cpp.o
        /tmp/pip-req-build-iLuIe4/python.cpp:22:10: fatal error: 'ydk/path_api.hpp' file not found
        #include <ydk/path_api.hpp>
                 ^~~~~~~~~~~~~~~~~~
        1 error generated.
        make[2]: *** [CMakeFiles/ydk_.dir/python.cpp.o] Error 1
        make[1]: *** [CMakeFiles/ydk_.dir/all] Error 2
        make: *** [all] Error 2
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/tmp/pip-req-build-iLuIe4/setup.py", line 151, in <module>
            zip_safe=False,
          File "/Users/khalil/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
            return distutils.core.setup(**attrs)
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
            dist.run_commands()
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
            self.run_command(cmd)
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/Users/khalil/anaconda2/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
            return orig.install.run(self)
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
            self.run_command('build')
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
            self.distribution.run_command(command)
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
            self.run_command(cmd_name)
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
            self.distribution.run_command(command)
          File "/Users/khalil/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/private/tmp/pip-req-build-iLuIe4/setup.py", line 74, in run
            self.build_extension(ext)
          File "/private/tmp/pip-req-build-iLuIe4/setup.py", line 107, in build_extension
            subprocess.check_call([cmake_executable, '--build', '.'], cwd=self.build_temp)
          File "/Users/khalil/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2
        
        ----------------------------------------
    Command "/Users/khalil/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-iLuIe4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-o_eOQZ/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-req-build-iLuIe4/ 

Obviously the error is occured in `'ydk/path_api.hpp'` where it is written that it is missed, but in fact, it is not. I double checked the folder `/usr/local/include/ydk/` where the file `path_api.hpp` exists in there.

  [1]: http://ydk.cisco.com/py/docs/getting_started.html

**Comment by khalilmebarkia** [comment]
have managed to install the package and run it on Docker in a remote server.

**Comment by valeriodigregorio** [comment]
How do you solve this without Docker?
