### ISSUE TITLE
Exception raised not all that helpful

### ISSUE THREAD

**Issue by einarnn** [CiscoDevNet/ydk-py#4]
I attempted what was, in some way, an invalid configuration operation, and received this exception:

```
Creating destination group...
Traceback (most recent call last):
  File "./ydk-mdt.py", line 313, in <module>
    prot=args.prot)
  File "./ydk-mdt.py", line 106, in xr_create_destination_group
    crud_service.create(session, dg)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/services/crud_service.py", line 56, in create
    self._execute_crud_operation_on_provider(provider, entity, 'CREATE', False)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/services/crud_service.py", line 145, in _execute_crud_operation_on_provider
    only_config
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/services/service.py", line 30, in execute_payload
    payload)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 91, in execute_operation
    return self._handle_rpc_reply(session_manager, payload, reply_str)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 112, in _handle_rpc_reply
    self._handle_rpc_ok(session_manager, payload, reply_str, separator)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 120, in _handle_rpc_ok
    self._handle_commit(session_manager, payload, reply_str, separator)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 133, in _handle_commit
    raise YPYError('Server reported an error while committing change!')
ydk.errors.YPYError: Server reported an error while committing change!
```

This is not a very helpful error. Looking into where the YPYError exception is raised:

```
    def _handle_commit(self, session_manager, payload, reply_str, separator):
        commit = session_manager.commit()
        if 'ok' not in commit.xml:
            self.netconf_sp_logger.error('%s\n%s\n%s\ncommit-reply\n%s\n%s', separator,
                                    payload, reply_str.xml, commit.xml, separator)
            raise YPYError('Server reported an error while committing change!')
        else:
            self.netconf_sp_logger.debug('%s\n%s\n%s\n\ncommit-reply\n%s\n%s', separator,
                                    payload, reply_str.xml, commit.xml, separator)
```

...we can see that, if enabled, logging will have better info, but the info needs to be present in the YPYError exception as well. In general, should examine the utility of the exceptions we re-raise as YDK exceptions that suppress the underlying exceptions and ensure that sufficient information is propagated to allow application developers to understand the error in a little more detail.

Probably also need to introduce enums, etc., for the YPYErrors to ensure developers don't start trying to parse the message strings we pass back.

Cheers,

Einar

**Comment by einarnn** [comment]
Another example of an exception not presenting useful information. In this case the app was attempting to delete non-existent data:

```
dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x10ea6acd0>: <?xml version="1.0"?>
<rpc-reply message-id="urn:uuid:ad29f270-f665-11e5-8f91-985aebd9a05c" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <rpc-error>
  <error-type>application</error-type>
  <error-tag>data-missing</error-tag>
  <error-severity>error</error-severity>
  <error-path xmlns:ns1="http://cisco.com/ns/yang/Cisco-IOS-XR-mgmt-mdt-cfg">ns1:m2m/ns1:mdt</error-path>
 </rpc-error>
</rpc-reply>

Delivering to <ydk.providers._provider_plugin._SP_RPC object at 0x10ea6ae50>
Traceback (most recent call last):
  File "./ydk-mdt.py", line 307, in <module>
    xr_delete_all(c, session)
  File "./ydk-mdt.py", line 21, in xr_delete_all
    return crud_service.delete(session, mdt)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/services/crud_service.py", line 77, in delete
    self._execute_crud_operation_on_provider(provider, entity, 'DELETE', False)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/services/crud_service.py", line 145, in _execute_crud_operation_on_provider
    only_config
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/services/service.py", line 30, in execute_payload
    payload)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 91, in execute_operation
    return self._handle_rpc_reply(session_manager, payload, reply_str)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 110, in _handle_rpc_reply
    self._handle_rpc_error(session_manager, payload, reply_str, pathlist, separator)
  File "/Users/einarnn/scratch/temp/ydk/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 126, in _handle_rpc_error
    raise YPYError('Server rejected request. Error reported:' + '. '.join([str(a) for a in pathlist]))
ydk.errors.YPYError: Server rejected request. Error reported:
dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x10ea6acd0>
```

Clearly there is more information in the underlying roc-reply than is propagated.

Cheers,

Einar

**Comment by psykokwak4** [comment]
As suggested, I tried to introduce a string Enum class YPYErrorCode(Enum) to errors module:
```python
class YPYErrorCode(Enum):
    INVALID_UNION_VALUE = 'Cannot translate union value'
    INVALID_ENCODE_VALUE = 'Cannot encode value'
    INVALID_HIERARCHY_PARENT = 'Parent is not set. \
                    Parent Hierarchy cannot be determined'
    INVALID_HIERARCHY_KEY = 'Key value is not set. \
                    Parent hierarchy cannot be constructed'
    INVALID_RPC = 'Object is not an RPC, cannot execute non-RPC object.'
    INVALID_MODIFY = 'Entity is read-only, cannot modify a read-only entity.'
    SERVER_REJ = 'Server rejected request.'
    SERVER_COMMIT_ERR = 'Server reported an error while committing change.'
```
and modify the YPYError class as:
```python
class YPYError(Exception):
    ''' Base Exception for YDK Errors '''
    def __init__(self, error_code, error_msg=None):
        self.error_code = error_code
        self.error_msg = error_msg

    def __str__(self):
        ret = [self.error_code.value]
        if self.error_msg is not None:
            parser = etree.XMLParser(remove_blank_text=True)
            root = etree.XML(self.error_msg.xml, parser)
            for r in root.iter():
                tag = r.tag[r.tag.rfind('}') + 1 :]
                if r.text is not None:
                    ret.append('\t{}: {}'.format(tag, r.text.strip()))
        return '\n'.join(ret)
```
The error_code attribute for YPYError is one of the above enum literal, and error_msg represents for underlying rpc-reply. So in the second example, error message will be propagated as:
```
YPYError: Server rejected request.
    error-type: application
    error-tag: data-missing
    error-severity: error
    error-path: ns1:m2m/ns1:mdt
```
And in the provider_plugin, string passed in to construct YPYError will be changed to enum literal for YPYErrorCode.
Is this something expected?

**Comment by abhikeshav** [comment]
I'd  confirm with @manradhacisco  about this proposal
